### ISSUE TITLE
export is not recognized : export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim

### ISSUE THREAD

**Issue by Javiersuing** [puigalex/deteccion_objetos#1]
Hola Alex, al replicar el tutorial de detección de objetos, me sale el error "export si not recognized : export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim", el cual según lo que veo, se debe a que mi compu usa el sistema operativo Windows. ¿Podrías generar una versión para usuarios de Windows o quizás darme unas pistas de como solucionarlo? 

Nota: Encontré en google que debería usar el siguiente comando: set PYTHONPATH=...\python\models;...\python\models\slim, sin embargo, creo que no me funciona porque tengo 2 versiones de python y la versión 3.6 la nombre python2. Intente un par de opciones, pero al tratar de ejecutar el siguiente comando: python xml_a_csv.py --inputs=img_test --output=test, me sale error. Agradezco tus comentarios.

**Comment by Javiersuing** [comment]
Finalmente lo solucioné de la siguiente forma:

En Windows se debe realizar lo siguiente:

 1. En lugar de ejecutar el comando export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
Ir desde el cmd (command prompt) a la carpeta descargada del GitHub de Alex y ejecutar los siguientes comandos (uno a la vez):
python setup.py build
python setup.py install
Nota: para ir a la carpeta usa el comando "cd",  en mi caso fue:
cd C:\Users\jasua\Downloads\deteccion-de-objetos

2. Luego ir a la carpeta slim con el comando cd (estando en la deteccion-de-objetos) y ejecutar el siguiente comando:

pip install -e .

3. Volver (desde el command prompt) a la carpeta principal, en mi caso la llame deteccion-de-objetos.
Nota: esto lo haces ejecutando el siguiente comando: cd ../

4. Ejecutar las otras 4 instrucciones del video de Alex (parte 2).

python xml_a_csv.py --inputs=img_test --output=test
python xml_a_csv.py --inputs=img_entrenamiento --output=entrenamiento
python csv_a_tf.py --csv_input=CSV/test.csv --output_path=TFRecords/test.record --images=images
python csv_a_tf.py --csv_input=CSV/entrenamiento.csv --output_path=TFRecords/entrenamiento.record --images=images

No obstante, seguramente saldrá un error, yo lo solucione creando en la carpeta principal una carpeta vacía llamada CSV y otra llamada TFRecords y listo.

5. Entrenar con el siguiente comando (Como se indica en el vídeo de Alex o en su blog):

python object_detection/train.py --logtostderr --train_dir=train --pipeline_config_path=modelo/faster_rcnn_resnet101_coco.config

Nota: En mi caso ejecuté primero el paso 4, luego del 1 al 3 y finalmente el 5.

**Comment by brpastran** [comment]
@Javiersuing lo pudiste pasar a colab sin problemas? a mí me tira error de memoria. Pasé todos los scripts y llego a empezar a entrenar, pero finaliza abruptamente con "^C". En local me pasa lo mismo. Saludos!

**Comment by Javiersuing** [comment]
Hola, lo de pasar a Colab lo pospuse porque mi objetivo en este momento no es reconocimiento de objetos, de hecho encontré algunos métodos más prácticos, que aspiro explorar más adelante y te comparto uno más abajo. Por ahora estoy centrado en CNN para problemas de regresión y clasificación y todo lo trabajo desde Colab, uniéndolo a mi DRIVE, de esa manera coloco los PATH y listo.

YOLO:
https://www.learnopencv.com/deep-learning-based-object-detection-using-yolov3-with-opencv-python-c/

Respecto a que te arroje problema locamente, pensaría que te falta alguno de los pasos del blog de Alex: https://inteligencia.tech/2019/02/24/deteccion-de-objetos-con-tensorflow/

En mi caso para el proyecto de los tigres, usé una computadora con Windows 10, procesador Intel Core i5 8th Gen, RAM de 4 Gigas y ya, nada especial. Al correrlo, el uso de CPU estaba al 100%, el ventilador estaba a todo dar y por supuesto estaba caliente el compu, así que decidí cortarlo como a las 200 épocas. También cree un ambiente para usar una versión de python compatible con tensorflow y todo lo ejecuté desde el Command prompt (cmd).

**Comment by LeanPerez21** [comment]
Hola buenas, a mi me tira el siguiente error:

File "csv_a_tf.py", line 13, in <module>
    from object_detection.utils import label_map_util
  File "C:\Users\Leandro\Desktop\deteccion_objetos-master\object_detection\utils\label_map_util.py", line 20, in <module>
    import tensorflow as tf
ModuleNotFoundError: No module named 'tensorflow'

Es como que no tengo instalado la libreria tensorflow, pero si la tengo, los csv me los creo correctamente, tnego este problema a la hora de crear los TFRecords (ya cree las carpetas)

**Comment by Javiersuing** [comment]
Hola Leandro,

Lo que recuerdo, es que tiene que ver con la librería utils, de hecho creo que estaba (deprecated) obsoleta, por lo que instalé Pillow (pip Pillow), en internet encuentras soluciones. Ahora bien ando un poco ocupado por estos días, por lo que si aún en Octubre, quieres completar el ejercicio, escribe nuevamente y valido con más calma.

Saludos.
________________________________

**Comment by LeanPerez21** [comment]
Ya está solucionado, te agradezco el tiempo que te has tomado en serio!
Muchas gracias y saludos de Argentina!

**Comment by Gabriel-Molinas** [comment]
Hola Javiersuing, La verdad es que soy nuevo en esto de la inteligencia artificial y todo este mundo, y todo esto me ayuda un montón. 
Seguí todos tus pasos pero me sale 
------------------------------------------------
Traceback (most recent call last):
  File "csv_a_tf.py", line 24, in <module>
    flags = tf.app.flags
AttributeError: module 'tensorflow' has no attribute 'app'
------------------------------------------------
Al ejecutar: python csv_a_tf.py --csv_input=CSV/test.csv --output_path=TFRecords/test.record --images=images

que puede ser?

**Comment by Javiersuing** [comment]
Hola,

En ocasiones es por compatibilidad en versiones de los programas y librerías que usas, en Google puedes encontrar varias opciones para conocer las versiones de los programas que usas, en mi caso uso pip list desde la ventana de comandos de Windows (cmd). Para poder descartar que sea por eso, debemos validar la versión de Python (3.6.8  o menor), la versión de TensorFlow (1.x) (la x quiere decir cualquier versión de las que empiezan por 1.) Puede ser de interés confirmar la versión del Matplotlib y la de Keras (respecto a pandas y numpy no he visto que molesten las últimas versiones), aunque para el detección de objetos de Alex puede que no las requieras. Otra posible causa es que este campo del conocimiento cambia constantemente, cada día con nuevas actualizaciones, y este ejercicio ya tiene un tiempo de haber salido, por lo que puede que dependa de alguna librería que se actualizó recientemente y esa sea la causa. Otra opción es que pongas el error que te sale en Google y leas los foros de solución de problemas como Stackoverflow.

Saludos

________________________________

**Comment by AlejoOrtega** [comment]
Hola @Javiersuing !

Acabo de replicar tu ejemplo de "Detección de objetos con tensorflow" pero por alguna razón al momento de realizar una predicción, el código finaliza sin haber realizado ninguna predicción.

Cabe resaltar que es el mismo ejemplo de los Tigres y tengo las mismas imágenes que dejaste en el repositorio!. Lo único que he cambiado hasta el momento son las imágenes prueba que iba a predecir.

![image](https://user-images.githubusercontent.com/43015395/73880183-e9b57b80-482b-11ea-90be-5997f1a0fadc.png)


Quedo atento!
Saludos

**Comment by AlejoOrtega** [comment]
Encontré el error! Las imágenes pruebas deben estar en formato **_.jpeg_** !!

**Comment by Javiersuing** [comment]
Hola Alejandro,

Puede ser hallas actualizado alguna librería y como resultado se presente la incompatibilidad. Para otros proyectos que estoy trabajando he tenido que regresar a versiones anteriores en algunas librerías. Sabes usar el comando pip list?

Saludos.

________________________________

**Comment by Javiersuing** [comment]
Que bien Alejandro, a veces eso pasa y aunque existen librerías que reconocen más formatos, es una práctica común usar un solo formato.

Saludos.

________________________________

**Comment by Juan-Moreno-17** [comment]
Hola amigos, para quienes no pudieron ejecutar los siguientes códigos: 

python csv_a_tf.py --csv_input=CSV/test.csv --output_path=TFRecords/test.record --images=images

python csv_a_tf.py --csv_input=CSV/entrenamiento.csv --output_path=TFRecords/entrenamiento.record --images=images

Es por un tema de versión con tensorflow, ya que actualmente se utilizar tensorflow 2.0 y el ejemplo es de tensorflow 1.x. Entonces para ello deben de llevar a su pip a una version anterior. Corriendo lo siguiente:
pip install pip==19.2.3
pip install tensorflow==1.14.0
Corriendo cada uno en el terminal podrán pasar los archivos csv a tfrecords.

Cabe resaltar que es para S.O. windows.

**Comment by Juan-Moreno-17** [comment]
En el caso que hayan terminado el ejemplo, me ayudarían bastante saber como lograron ejecutar la parte del entrenamiento, en el sistema operativo Windows, ya que a mi me sale el siguiente error:

File "object_detection/train.py", line 51, in <module>
    from object_detection import trainer
  File "C:\Users\51999\Anaconda3\lib\site-packages\object_detection-0.1-py3.7.egg\object_detection\trainer.py", line 33, in <module>
    from deployment import model_deploy
ModuleNotFoundError: No module named 'deployment'

Después de haber corrido el siguiente código: 
python object_detection/train.py --logtostderr --train_dir=train --pipeline_config_path=modelo/faster_rcnn_resnet101_coco.config

**Comment by Calixto09** [comment]
# Solución al problema de Juan-Moreno-17
Buenas Moreno777, me pasó el mismo problema. 

Para solucionarlo tienes que irte a la carpeta de _slim_ que está dentro del repositorio que descargaste de Alex. Una vez ahí, copias los folders **deployment** y **nets** y lo pegas en Librery y Lib que están ubicadas en el directorio donde se instaló Anaconda. 

Para acceder al dirrectorio, puedes escribir en el buscador de Windows la aplicación Anaconda Navigator. Luego, haz click derecho en ella y presiona "Abrir ubicación del archivo". Si tienes suerte, te redireccionará automáticamente a la carpeta en donde se instaló dicho programa. Sino, te redireccionará al acceso directo del mismo. Bueno, de ser el último caso, es más que suficiente hacer click derecho en el accseo directo y volver a presionar "Abrir ubicación del archivo". Una vez ahí, busca las carpetas de Lib y Library para pegar las que al principio copeaste. 

Pueda que el programa requiera otras carpetas más. De ser así, aplica el mismo procedimiento para la nueva carpeta. 

Espero que esto haya sido de tu ayuda.

**Comment by Elq-eng** [comment]
Buenas Tardes 

me ayudarían bastante saber como lograron ejecutar la parte del entrenamiento, en el sistema operativo Windows, ya que a mi me sale el siguiente error:

 File "object_detection/train.py", line 51, in <module>
    from object_detection import trainer
ImportError: cannot import name 'trainer'

Después de haber corrido el siguiente código:
python object_detection/train.py --logtostderr --train_dir=train --pipeline_config_path=modelo/faster_rcnn_resnet101_coco.config

**Comment by Elq-eng** [comment]
Hola @AlejoOrtega 

lo que sucede es que me aparece el  mismo error y no me muestra las imagenes prueba, no se porque, las immagenes estan en .jpg no se como podria solucionarlo porque no aparece mucha informacion. 

![imagen](https://user-images.githubusercontent.com/68078777/87859155-97a77480-c8f8-11ea-9024-3f167ceb2940.png)

de antemano muchas gracias por la ayuda

**Comment by AlfredMoller** [comment]
> Finalmente lo solucioné de la siguiente forma:
> 
> En Windows se debe realizar lo siguiente:
> 
> 1. En lugar de ejecutar el comando export PYTHONPATH=$PYTHONPATH:`pwd`:`pwd`/slim
>    Ir desde el cmd (command prompt) a la carpeta descargada del GitHub de Alex y ejecutar los siguientes comandos (uno a la vez):
>    python setup.py build
>    python setup.py install
>    Nota: para ir a la carpeta usa el comando "cd",  en mi caso fue:
>    cd C:\Users\jasua\Downloads\deteccion-de-objetos
> 2. Luego ir a la carpeta slim con el comando cd (estando en la deteccion-de-objetos) y ejecutar el siguiente comando:
> 
> pip install -e .
> 
> 1. Volver (desde el command prompt) a la carpeta principal, en mi caso la llame deteccion-de-objetos.
>    Nota: esto lo haces ejecutando el siguiente comando: cd ../
> 2. Ejecutar las otras 4 instrucciones del video de Alex (parte 2).
> 
> python xml_a_csv.py --inputs=img_test --output=test
> python xml_a_csv.py --inputs=img_entrenamiento --output=entrenamiento
> python csv_a_tf.py --csv_input=CSV/test.csv --output_path=TFRecords/test.record --images=images
> python csv_a_tf.py --csv_input=CSV/entrenamiento.csv --output_path=TFRecords/entrenamiento.record --images=images
> 
> No obstante, seguramente saldrá un error, yo lo solucione creando en la carpeta principal una carpeta vacía llamada CSV y otra llamada TFRecords y listo.
> 
> 1. Entrenar con el siguiente comando (Como se indica en el vídeo de Alex o en su blog):
> 
> python object_detection/train.py --logtostderr --train_dir=train --pipeline_config_path=modelo/faster_rcnn_resnet101_coco.config
> 
> Nota: En mi caso ejecuté primero el paso 4, luego del 1 al 3 y finalmente el 5.

Buenas amigo, te escribo desde Paraguay, soy nuevo en esto de la IA, quisiera consultarte cual sería la línea de comando para congelar el modelo que estuve entrenando y predecir por el Command Prompt en Windows , basado en el vídeo de Alex Puig. Te dejo mi correo: almoller622@gmail.com
De antemano muchas gracias!!!

**Comment by snoemiperez** [comment]
Hola, 
tengo el mismo problema de @Juan-Moreno-17. O sea, el comando
python object_detection/train.py --logtostderr --train_dir=train --pipeline_config_path=modelo/faster_rcnn_resnet101_coco.config

me tira el sig error:
python: can't open file 'object_detection/train.py': [Errno 2] No such file or directory

No me funcionó lo de copiar las carpetas deployment y nets.
Alguna sugerencia?

**Comment by AlfredMoller** [comment]
Buenas... Si llegaste a realizarlo en Windows:

1- En lugar de ejecutar el comando export
PYTHONPATH=$PYTHONPATH:pwd:pwd/slim
Ir desde el cmd (command prompt) a la carpeta descargada del GitHub de Alex
y ejecutar los siguientes comandos (uno a la vez):
python setup.py build
python setup.py install
Nota: para ir a la carpeta usa el comando "cd", en mi caso fue:
cd C:\Users\jasua\Downloads\deteccion-de-objetos

2- Luego ir a la carpeta slim con el comando cd (estando en la
deteccion-de-objetos) y ejecutar el siguiente comando:

pip install -e .

3- Volver (desde el command prompt) a la carpeta principal, en mi caso la
llame deteccion-de-objetos.
Nota: esto lo haces ejecutando el siguiente comando: cd ../

4-Ejecutar las otras 4 instrucciones del video de Alex (parte 2).

python xml_a_csv.py --inputs=img_test --output=test
python xml_a_csv.py --inputs=img_entrenamiento --output=entrenamiento
python csv_a_tf.py --csv_input=CSV/test.csv
--output_path=TFRecords/test.record --images=images
python csv_a_tf.py --csv_input=CSV/entrenamiento.csv
--output_path=TFRecords/entrenamiento.record --images=images

No obstante, seguramente saldrá un error, yo lo solucione creando en la
carpeta principal una carpeta vacía llamada CSV y otra llamada TFRecords y
listo.

5- Entrenar con el siguiente comando (Como se indica en el vídeo de Alex o
en su blog):
python object_detection/train.py --logtostderr --train_dir=train
--pipeline_config_path=modelo/faster_rcnn_resnet101_coco.config

Nota: Ejecutar primero el paso 4, luego del 1 al 3 y finalmente el 5.

Podría compartirte en un Drive la carpta de Slim si estás en apuros, este
es mi correo ***@***.***

**Comment by snoemiperez** [comment]
gracias @AlfredMoller 
si, esos pasos seguí y no funcionaba el paso de entrenar el modelo.
Después hice también lo de copiar las carpetas a Lib, y correr el comando de entrenar, y me tiró
ModuleNotFoundError: No module named 'tf_slim'
entonces corrí en la carpeta object_detection
pip install tf_slim
Así finalmente pude correr el comando para entrenar y .. fin.

**Comment by jorge-nt** [comment]
Hola, tengo el mismo problema que  @brpastran , corro el código en Google Colab pero tengo error de memoria y se  finaliza con "^C" , alguien ha podido hacerlo funcionar en Colab?
